!
! test_TELSEM2_Covariance
!
! Validate the TELSEM2 Release-2 uncertainty content and the emissivity error
! covariance machinery against the RTTOV reference implementation
! (mod_mwatlas_m2.F90), plus the class accessor and the query-API error paths.
!
! The golden values in telsem2_covariance_goldens.inc were generated by running
! the stand-alone RTTOV reference on the original ASCII atlas distribution
! (emis_interp_ind_mult / emis_interp_int_mult / *_sing with the std outputs)
! for a probe set spanning the class space: vegetated (class2 1), desert (5),
! continental ice (20), seasonal snow (17), at native resolution and with
! 1-degree spatial averaging, below and above the 85.5 GHz anchor. The CRTM
! port keeps the reference operation order, so agreement is expected at the
! last-ulp level; the tolerance below leaves headroom for compiler differences
! while remaining far tighter than any scientific requirement.
!
! Sections:
!   1. Query-API guard: FAILURE before any atlas is loaded.
!   2. Load the Release-2 atlas directly via CRTM_MWlandCoeff_Load.
!   3. Golden comparisons (emissivities + full 2n x 2n covariance).
!   4. Single-frequency std/covariance goldens (TELSEM2_Emissivity_Std).
!   5. Class accessor spot checks (veg/desert/ice/snow/seasonal/ocean).
!   6. Covariance structure: symmetry and non-negative variances.
!   7. Error paths: dimension mismatch; Release-1 (no-uncertainty) atlas.
!   8. Thread safety: identical results from concurrent queries.
!   9. Release-1 fixture round-trip: a no-uncertainty structure writes a
!      Release-1 file that reads back with Has_Uncertainty = .FALSE..
!
PROGRAM test_TELSEM2_Covariance

  USE CRTM_Module
  USE CRTM_MWlandCoeff      , ONLY: CRTM_MWlandCoeff_Load   , &
                                    CRTM_MWlandCoeff_Destroy, &
                                    MWlandC
  USE TELSEM2_Atlas_Module  , ONLY: TELSEM2_Class          , &
                                    TELSEM2_Emissivity     , &
                                    TELSEM2_Emissivity_Std
  USE TELSEM2Atlas_Define   , ONLY: TELSEM2Atlas_type      , &
                                    TELSEM2Atlas_Create    , &
                                    TELSEM2Atlas_Destroy   , &
                                    TELSEM2Atlas_Associated
  USE TELSEM2Atlas_netCDF_IO, ONLY: TELSEM2Atlas_netCDF_WriteFile, &
                                    TELSEM2Atlas_netCDF_ReadFile
  IMPLICIT NONE

  CHARACTER(*), PARAMETER :: PROGRAM_NAME = 'test_TELSEM2_Covariance'
  CHARACTER(*), PARAMETER :: ATLAS_FILE   = './testinput/TELSEM2.MWland.test.nc'
  CHARACTER(*), PARAMETER :: R1_FIXTURE   = './testinput/telsem2_r1_fixture.nc'

  REAL(fp), PARAMETER :: THETA    = 15.0_fp
  REAL(fp), PARAMETER :: TOL_GOLD = 1.0E-13_fp
  ! Probe points (see class expectations in section 5)
  REAL(fp), PARAMETER :: LAT_ARG = -30.0_fp, LON_ARG = 302.0_fp  ! Argentina veg
  REAL(fp), PARAMETER :: LAT_SAH =  21.0_fp, LON_SAH =  10.0_fp  ! Sahara desert
  REAL(fp), PARAMETER :: LAT_GRL =  72.0_fp, LON_GRL = 320.0_fp  ! Greenland ice
  REAL(fp), PARAMETER :: LAT_IOW =  42.0_fp, LON_IOW = 266.0_fp  ! Iowa cropland
  REAL(fp), PARAMETER :: LAT_OCN =   0.0_fp, LON_OCN = 200.0_fp  ! open ocean
  ! Frequency sets matching the golden generator
  REAL(fp), PARAMETER :: FREQS_A(3) = [ 23.8_fp, 31.4_fp, 50.3_fp ]
  REAL(fp), PARAMETER :: FREQS_B(4) = [ 23.8_fp, 88.2_fp, 165.5_fp, 183.31_fp ]

  INCLUDE 'telsem2_covariance_goldens.inc'

  CHARACTER(256) :: Message, Version
  INTEGER  :: err, i, j, c1, c2
  LOGICAL  :: failed, valid, ok
  REAL(fp) :: ev3(3), eh3(3), cov6(6,6)
  REAL(fp) :: ev4(4), eh4(4), cov8(8,8)
  REAL(fp) :: ev, eh, stdv, stdh, covvh
  REAL(fp) :: bad_cov(3,3)
  REAL(fp) :: par_ev(3,8), par_eh(3,8), par_cov(6,6,8)
  INTEGER  :: par_err(8)
  LOGICAL  :: par_valid(8)
  TYPE(TELSEM2Atlas_type) :: fixture

  CALL CRTM_Version( Version )
  CALL Program_Message( PROGRAM_NAME, &
    'Validate the TELSEM2 emissivity error covariance against the RTTOV reference.', &
    'CRTM Version: '//TRIM(Version) )
  failed = .FALSE.

  ! ------------------------------------------------------------------
  ! 1. Query before load must fail cleanly
  ! ------------------------------------------------------------------
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_A, &
                                             ev3, eh3, cov6, valid, Zenith_Angle=THETA )
  CALL Expect( err == FAILURE, 'query before load returns FAILURE' )

  ! ------------------------------------------------------------------
  ! 2. Load the Release-2 atlas
  ! ------------------------------------------------------------------
  err = CRTM_MWlandCoeff_Load( ATLAS_FILE )
  IF ( err /= SUCCESS ) THEN
    CALL Display_Message( PROGRAM_NAME, 'Error loading TELSEM2 atlas', FAILURE ); STOP 1
  END IF
  CALL Expect( CRTM_MWlandCoeff_IsLoaded(), 'atlas reports loaded' )
  CALL Expect( MWlandC%Has_Uncertainty, 'Release-2 atlas carries uncertainty' )

  ! ------------------------------------------------------------------
  ! 3. Golden comparisons: multi-channel emissivity + covariance
  ! ------------------------------------------------------------------
  ! 3a. Argentina veg, Sep, AMSU-A lows, native resolution
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_A, &
                                             ev3, eh3, cov6, valid, Zenith_Angle=THETA )
  CALL Expect( err == SUCCESS .AND. valid, 'query (ARG/Sep/A3/native) succeeds' )
  CALL Assert_Gold( ev3, GOLD_ARG_SEP_A3_NAT_EV, 'ARG_SEP_A3_NAT EV' )
  CALL Assert_Gold( eh3, GOLD_ARG_SEP_A3_NAT_EH, 'ARG_SEP_A3_NAT EH' )
  CALL Assert_Gold( RESHAPE(cov6,[36]), GOLD_ARG_SEP_A3_NAT_STD_FLAT, 'ARG_SEP_A3_NAT STD' )

  ! 3b. Argentina veg, Sep, ATMS-like set incl. >85 GHz, 1-degree averaging
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_B, &
                                             ev4, eh4, cov8, valid, Zenith_Angle=THETA, &
                                             Resolution=1.0_fp )
  CALL Expect( err == SUCCESS .AND. valid, 'query (ARG/Sep/B4/resol=1) succeeds' )
  CALL Assert_Gold( ev4, GOLD_ARG_SEP_B4_RES1_EV, 'ARG_SEP_B4_RES1 EV' )
  CALL Assert_Gold( eh4, GOLD_ARG_SEP_B4_RES1_EH, 'ARG_SEP_B4_RES1 EH' )
  CALL Assert_Gold( RESHAPE(cov8,[64]), GOLD_ARG_SEP_B4_RES1_STD_FLAT, 'ARG_SEP_B4_RES1 STD' )

  ! 3c. Sahara desert, Sep, native
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_SAH, LON_SAH, 9, FREQS_A, &
                                             ev3, eh3, cov6, valid, Zenith_Angle=THETA )
  CALL Expect( err == SUCCESS .AND. valid, 'query (SAH/Sep/A3/native) succeeds' )
  CALL Assert_Gold( ev3, GOLD_SAH_SEP_A3_NAT_EV, 'SAH_SEP_A3_NAT EV' )
  CALL Assert_Gold( eh3, GOLD_SAH_SEP_A3_NAT_EH, 'SAH_SEP_A3_NAT EH' )
  CALL Assert_Gold( RESHAPE(cov6,[36]), GOLD_SAH_SEP_A3_NAT_STD_FLAT, 'SAH_SEP_A3_NAT STD' )

  ! 3d. Greenland continental ice, Jan, incl. >85 GHz, native
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_GRL, LON_GRL, 1, FREQS_B, &
                                             ev4, eh4, cov8, valid, Zenith_Angle=THETA )
  CALL Expect( err == SUCCESS .AND. valid, 'query (GRL/Jan/B4/native) succeeds' )
  CALL Assert_Gold( ev4, GOLD_GRL_JAN_B4_NAT_EV, 'GRL_JAN_B4_NAT EV' )
  CALL Assert_Gold( eh4, GOLD_GRL_JAN_B4_NAT_EH, 'GRL_JAN_B4_NAT EH' )
  CALL Assert_Gold( RESHAPE(cov8,[64]), GOLD_GRL_JAN_B4_NAT_STD_FLAT, 'GRL_JAN_B4_NAT STD' )

  ! 3e. Iowa seasonal snow, Jan, native
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_IOW, LON_IOW, 1, FREQS_A, &
                                             ev3, eh3, cov6, valid, Zenith_Angle=THETA )
  CALL Expect( err == SUCCESS .AND. valid, 'query (IOWA/Jan/A3/native) succeeds' )
  CALL Assert_Gold( ev3, GOLD_IOWA_JAN_A3_NAT_EV, 'IOWA_JAN_A3_NAT EV' )
  CALL Assert_Gold( eh3, GOLD_IOWA_JAN_A3_NAT_EH, 'IOWA_JAN_A3_NAT EH' )
  CALL Assert_Gold( RESHAPE(cov6,[36]), GOLD_IOWA_JAN_A3_NAT_STD_FLAT, 'IOWA_JAN_A3_NAT STD' )

  ! ------------------------------------------------------------------
  ! 4. Single-frequency std goldens
  ! ------------------------------------------------------------------
  ! 4a. Argentina, 30 GHz, native
  CALL TELSEM2_Emissivity( MWlandC, LAT_ARG, LON_ARG, 9, 30.0_fp, THETA, ev, eh, valid )
  CALL TELSEM2_Emissivity_Std( MWlandC, LAT_ARG, LON_ARG, 9, 30.0_fp, stdv, stdh, covvh, valid )
  CALL Assert_Gold( [ev, eh, stdv, stdh, covvh], GOLD_ARG_SEP_SING30, 'ARG_SEP_SING30 (ev,eh,stdv,stdh,covvh)' )

  ! 4b. Greenland, 89 GHz, 1-degree averaging
  CALL TELSEM2_Emissivity( MWlandC, LAT_GRL, LON_GRL, 1, 89.0_fp, THETA, ev, eh, valid, &
                           Resolution=1.0_fp )
  CALL TELSEM2_Emissivity_Std( MWlandC, LAT_GRL, LON_GRL, 1, 89.0_fp, stdv, stdh, covvh, valid, &
                               Resolution=1.0_fp )
  CALL Assert_Gold( [ev, eh, stdv, stdh, covvh], GOLD_GRL_JAN_SING89_RES1, &
                    'GRL_JAN_SING89_RES1 (ev,eh,stdv,stdh,covvh)' )

  ! ------------------------------------------------------------------
  ! 5. Class accessor spot checks
  ! ------------------------------------------------------------------
  CALL TELSEM2_Class( MWlandC, LAT_ARG, LON_ARG, 9, c1, c2, valid )
  CALL Expect( valid .AND. c1 == 1 .AND. c2 == 1, 'class (ARG/Sep) = vegetation (1,1)' )
  CALL TELSEM2_Class( MWlandC, LAT_SAH, LON_SAH, 9, c1, c2, valid )
  CALL Expect( valid .AND. c1 == 5 .AND. c2 == 5, 'class (SAH/Sep) = desert (5,5)' )
  CALL TELSEM2_Class( MWlandC, LAT_GRL, LON_GRL, 1, c1, c2, valid )
  CALL Expect( valid .AND. c1 == 6 .AND. c2 == 20, 'class (GRL/Jan) = continental ice (6,20)' )
  CALL TELSEM2_Class( MWlandC, LAT_IOW, LON_IOW, 1, c1, c2, valid )
  CALL Expect( valid .AND. c1 == 9 .AND. c2 == 17, 'class (IOWA/Jan) = seasonal snow (9,17)' )
  CALL TELSEM2_Class( MWlandC, LAT_IOW, LON_IOW, 9, c1, c2, valid )
  CALL Expect( valid .AND. c1 == 2 .AND. c2 == 2, 'class (IOWA/Sep) = vegetation (2,2)' )
  CALL TELSEM2_Class( MWlandC, LAT_OCN, LON_OCN, 9, c1, c2, valid )
  CALL Expect( (.NOT. valid) .AND. c1 == 0 .AND. c2 == 0, 'class (ocean) = no data' )

  ! ------------------------------------------------------------------
  ! 6. Covariance structure: symmetric with non-negative variances
  ! ------------------------------------------------------------------
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_GRL, LON_GRL, 1, FREQS_B, &
                                             ev4, eh4, cov8, valid, Zenith_Angle=THETA )
  ok = .TRUE.
  DO i = 1, 8
    IF ( cov8(i,i) < ZERO ) ok = .FALSE.
    DO j = 1, 8
      IF ( ABS(cov8(i,j)-cov8(j,i)) > TOL_GOLD ) ok = .FALSE.
    END DO
  END DO
  CALL Expect( ok, 'covariance symmetric with non-negative variances' )

  ! ------------------------------------------------------------------
  ! 7. Error paths
  ! ------------------------------------------------------------------
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_A, &
                                             ev3, eh3, bad_cov, valid )
  CALL Expect( err == FAILURE, 'dimension mismatch returns FAILURE' )
  ! Simulate a Release-1 (no-uncertainty) load
  MWlandC%Has_Uncertainty = .FALSE.
  err = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_A, &
                                             ev3, eh3, cov6, valid )
  CALL Expect( err == FAILURE, 'no-uncertainty atlas returns FAILURE' )
  MWlandC%Has_Uncertainty = .TRUE.

  ! ------------------------------------------------------------------
  ! 8. Thread safety: concurrent queries reproduce the serial result
  ! ------------------------------------------------------------------
  !$OMP PARALLEL DO PRIVATE(i)
  DO i = 1, 8
    par_err(i) = CRTM_TELSEM2_Emissivity_Uncertainty( LAT_ARG, LON_ARG, 9, FREQS_A, &
                   par_ev(:,i), par_eh(:,i), par_cov(:,:,i), par_valid(i), &
                   Zenith_Angle=THETA )
  END DO
  !$OMP END PARALLEL DO
  DO i = 1, 8
    CALL Expect( par_err(i) == SUCCESS .AND. par_valid(i), 'concurrent query succeeds' )
    CALL Assert_Gold( par_ev(:,i), GOLD_ARG_SEP_A3_NAT_EV, 'concurrent EV identical' )
    CALL Assert_Gold( RESHAPE(par_cov(:,:,i),[36]), GOLD_ARG_SEP_A3_NAT_STD_FLAT, &
                      'concurrent STD identical' )
  END DO

  err = CRTM_MWlandCoeff_Destroy()
  CALL Expect( .NOT. CRTM_MWlandCoeff_IsLoaded(), 'atlas destroyed' )

  ! ------------------------------------------------------------------
  ! 9. Release-1 fixture round-trip (small synthetic atlas, no uncertainty)
  ! ------------------------------------------------------------------
  CALL TELSEM2Atlas_Create( fixture, 7_Long, 720_Long, 660066_Long, 12_Long, 10_Long )
  fixture%Resolution = 0.25_fp
  fixture%Month_Data_Count    = 0
  fixture%Month_Data_Count(1) = 10
  fixture%Month_Offset        = 10
  fixture%Month_Offset(1)     = 0
  DO i = 1, 10
    fixture%Cell_Number(i) = i
    fixture%Class1(i)      = MIN(i,10)
    fixture%Class2(i)      = MIN(i,10)
    fixture%Emissivity(i,:) = 0.9_fp
  END DO
  err = TELSEM2Atlas_netCDF_WriteFile( R1_FIXTURE, fixture )
  CALL Expect( err == SUCCESS, 'no-uncertainty structure writes (as Release 1)' )
  CALL TELSEM2Atlas_Destroy( fixture )
  err = TELSEM2Atlas_netCDF_ReadFile( R1_FIXTURE, fixture )
  CALL Expect( err == SUCCESS .AND. TELSEM2Atlas_Associated(fixture), 'Release-1 file reads back' )
  CALL Expect( fixture%Release == 1 .AND. .NOT. fixture%Has_Uncertainty, &
               'Release-1 read has no uncertainty' )
  CALL TELSEM2Atlas_Destroy( fixture )

  ! ------------------------------------------------------------------
  ! Report
  ! ------------------------------------------------------------------
  IF ( failed ) THEN
    CALL Display_Message( PROGRAM_NAME, 'FAILED', FAILURE ); STOP 1
  ELSE
    CALL Display_Message( PROGRAM_NAME, &
      'PASSED: covariance machinery matches the RTTOV reference; class accessor, '// &
      'error paths, thread safety and Release-1 compatibility verified', &
      INFORMATION ); STOP 0
  END IF

CONTAINS

  SUBROUTINE Expect( cond, label )
    LOGICAL,      INTENT(IN) :: cond
    CHARACTER(*), INTENT(IN) :: label
    IF ( cond ) THEN
      WRITE(*,'(5x,"ok: ",a)') label
    ELSE
      CALL Display_Message( PROGRAM_NAME, 'Expectation failed: '//label, FAILURE )
      failed = .TRUE.
    END IF
  END SUBROUTINE Expect

  SUBROUTINE Assert_Gold( a, gold, label )
    REAL(fp),     INTENT(IN) :: a(:), gold(:)
    CHARACTER(*), INTENT(IN) :: label
    REAL(fp) :: d
    d = MAXVAL(ABS(a-gold))
    IF ( d > TOL_GOLD ) THEN
      WRITE(Message,'("Golden mismatch: ",a," max |diff| = ",es13.5)') label, d
      CALL Display_Message( PROGRAM_NAME, TRIM(Message), FAILURE )
      failed = .TRUE.
    ELSE
      WRITE(*,'(5x,"ok: ",a," (max |diff| = ",es9.2,")")') label, d
    END IF
  END SUBROUTINE Assert_Gold

END PROGRAM test_TELSEM2_Covariance
